### ISSUE TITLE
License for marketplace item and embedded Wirecloud

### ISSUE THREAD

**Issue by markrey** [Wirecloud/wirecloud#219]
Hi,

This is amazing software you guys have designed.
I am planning to develop POC with custom graph types.

1. What would be the license for the same ? Do I have to disclose original source code in AGPL form ? 
I actually can't because those graphics JS libraries can not be sublicensed.

2. Is there any possiblity to embed Wirecloud inside my software ? Reason is security ( of course I will contribute back if i find issues in public wirecloud ).
for example I would like to use Wirecloud as it is ( with different branding of the project ) and embed it fully in another software which has API access to internal objects and proper role based access control.

3. Is there commercial version available ?

Thanks

**Comment by markrey** [comment]
for my question number 1, i got the answer as it has classpath exception which will allow me to create UI components.

**Comment by aarranz** [comment]
Hi markrey,

> 1. What would be the license for the same ? Do I have to disclose original source code in AGPL form ? 
I actually can't because those graphics JS libraries can not be sublicensed.

Yeah, we have added a classpath exception to the AGPL license (It's the first paragraph in our [LICENSE.txt](https://github.com/Wirecloud/wirecloud/blob/develop/LICENSE.txt) file). You can use any license for your widgets/operators without any problem.

> 2. Is there any possiblity to embed Wirecloud inside my software ? Reason is security ( of course I will contribute back if i find issues in public wirecloud ).
for example I would like to use Wirecloud as it is ( with different branding of the project ) and embed it fully in another software which has API access to internal objects and proper role based access control.

Technically, yes. But you will have to take into account the current license of WireCloud: AGPLv3+ with a classpath-like exception. This probably means that you will have to release your software under the AGPLv3+ license, depending on the architecture and on the way you distribute your software.

> 3. Is there commercial version available ?

Currently we're working on offering commercial support to WireCloud. We're estimating late summer for having it ready, though this is an estimation.

Best regards

**Comment by markrey** [comment]
Thank you very much @aarranz .. Understood. 
Due to AGPL restriction I might have to skip Wirecloud as security architecture is proprietary system.
Still finding another way to solve the same for POC.

Regards

**Comment by markrey** [comment]
@aarranz Other than commercial support, are you planning to open Wirecloud as more corporate and government project friendly license ( not GPL ) ? That might be commercial license as well.

**Comment by aarranz** [comment]
Hi @markrey, sorry for the delay, but we were on vacations.

Yeah, one of the options we are considering is to provide WireCloud using a dual license, being the other a comercial license. We are still working on how to provide our commercial support to the general public, but don't hesitate to contact us (by sending a message to wirecloud@conwet.com) for discussing the particular requirements you have for the commercial support.

Regards.
