### ISSUE TITLE
About making a message file.

### ISSUE THREAD

**Issue by fisuda** [Wirecloud/wirecloud#325]
When I ran the 'django-admin' command at 'wirecloud/platform' directory, I encountered the following errors. May I ignore it? or Should I do something?

$ pwd
/home/fisuda/work/wirecloud/src/wirecloud/platform
$ django-admin makemessages -l ja
UnicodeDecodeError: skipped file xhtml1-iso8859-15-expected.html in ./widget/test-data (reason: 'utf-8' codec can't decode byte 0xf1 in position 917: invalid continuation byte)
UnicodeDecodeError: skipped file xhtml1-iso8859-15-initial.html in ./widget/test-data (reason: 'utf-8' codec can't decode byte 0xf1 in position 297: invalid continuation byte)
UnicodeDecodeError: skipped file xhtml2-iso8859-15-expected.html in ./widget/test-data (reason: 'utf-8' codec can't decode byte 0xf1 in position 824: invalid continuation byte)
UnicodeDecodeError: skipped file xhtml2-iso8859-15-initial.html in ./widget/test-data (reason: 'utf-8' codec can't decode byte 0xf1 in position 351: invalid continuation byte)

**Comment by aarranz** [comment]
Hi @fisuda!

Sorry for the late response, yes, you can ignore them. Those errors raise because Django tries to parse them to search for translations, but they are html files used for testing (so those errors were added intentionally). It would be great to to make Django ignore those files, as they are not used in production, but currently they are raising.

Cheers!

**Comment by fisuda** [comment]
Hello @aarranz

Thanks for your answer. I understand this issue.
I'm trying to make po file in Japanese. Once I have successfully, I will send PR on Github.

Best regards,
