### ISSUE TITLE
WireCloud Installer

### ISSUE THREAD

**Issue by xaviersand** [Wirecloud/wirecloud#45]
When following the tutorial, 

running this command :
`(ENV)root@ubuntu:/opt# wirecloud-admin startproject wirecloud_instance --quick-start`

results to this error:

```Traceback (most recent call last):
  File "/usr/local/bin/wirecloud-admin", line 7, in <module>
    from wirecloud.commons.wirecloud_admin import execute_from_command_line
  File "/usr/local/lib/python2.7/dist-packages/wirecloud/commons/wirecloud_admin.py", line 23, in <module>
    from django.core.management import LaxOptionParser
ImportError: cannot import name LaxOptionParser```

But i could not find any package name laxoptionparser for ubuntu..

**Comment by aarranz** [comment]
WireCloud requires Django>=1.4.2,<1.7

**Comment by xaviersand** [comment]
Thanks for this.

Now when running any "manage.py" related command, i get this.

```$ python manage.py syncdb --migrate
python: can't open file 'manage.py': [Errno 2] No such file or directory```

but i don't know at which step this file should be created. 
I followed the tutorial, step by step but i do not understand this..

**Comment by aarranz** [comment]
The `manage.py` script is created by running the `wirecloud-admin startproject` command. Following your log, it should be available at `/opt/wirecloud_instance/manage.py`.

Thanks for reporting those problems in the installation guide, we have update it. The only thing that we have not addressed is the use of the `sudo` command, we need to study how to make it more clear. The idea is that you only need to use `sudo` for system-wide installations. For example, al those `apt-get install` lines need the use of `sudo` because `apt-get` only install packages directly on the system, whereas the creation of the virtualenv and the `pip install` lines don't require the use of sudo. You only need a user with permissions for creating and writing on the virtualenv directory in those cases. We will try to update the installation and administration guide ASAP.
